#ifndef COLOR_H__
#define COLOR_H__


#define clrAliceBlue					0xF0F8FF        //--艾利斯兰-->
#define clrAntiqueWhite                0xFAEBD7        //--古董白-->
#define clrAqua						0x00FFFF        //--浅绿色-->
#define clrAquamarine					0x7FFFD4        //--碧绿色-->
#define clrAzure						0xF0FFFF        //--天蓝色-->
#define clrBeige						0xF5F5DC        //--米色-->
#define clrBisque						0xFFE4C4        //--桔黄颜色-->
#define clrBlack						0x000000        //--黑色-->
#define clrBlanchedalmond              0xFFEBCD        //--白杏色-->
#define clrBlue						0x0000FF        //--蓝色-->
#define clrBlueViolet					0x8A2BE2        //--紫罗兰蓝色-->
#define clrBrown						0xA52A2A        //--褐色-->
#define clrBurlywood					0xDEB887        //--实木色-->
#define clrCadetBlue					0x5F9EA0        //--军兰色-->
#define clrChartreuse					0x7FFF00        //--黄绿色-->
#define clrChocolate					0xD2691E        //--巧可力色-->
#define clrCoral						0xFF7F50        //--珊瑚色-->
#define clrCornflowerblue              0x6495ED        //--菊兰色-->
#define clrCornsilk					0xFFF8DC        //--米绸色-->
#define clrCrimson						0xDC143C        //--暗深红色-->
#define clrCyan						0x00FFFF        //--青色-->
#define clrDarkBlue					0x00008B        //--暗蓝色-->
#define clrDarkCyan					0x008B8B        //--暗青色-->
#define clrDarkGoldenrod               0xB8860B        //--暗金黄颜色-->
#define clrDarkGray					0xA9A9A9        //--暗灰色-->
#define clrDarkGreen					0x006400        //--暗绿色-->
#define clrDarkGrey					0xA9A9A9        //--暗灰色-->
#define clrDarkkhaki					0xBDB76B        //--暗黄褐色-->
#define clrDarkMagenta                 0x8B008B        //--暗洋红-->
#define clrDarkOliveGreen              0x556B2F        //--暗橄榄绿-->
#define clrDarkOrange					0xFF8C00        //--暗桔黄颜色-->
#define clrDarkOrchid					0x9932CC        //--暗紫色-->
#define clrDarkRed						0x8B0000        //--暗红色-->
#define clrDarkSalmon					0xE9967A        //--暗肉色-->
#define clrDarkSeaGreen                0x8FBC8F        //--暗海兰色-->
#define clrDarkSlateBlue               0x483D8B        //--暗灰蓝色-->
#define clrDarkSlateGray               0x2F4F4F        //--暗瓦灰色-->
#define clrDarkSlateGrey               0x2F4F4F        //--暗瓦灰色-->
#define clrDarkTurquoise               0x00CED1        //--暗宝石绿-->
#define clrDarkViolet					0x9400D3        //--暗紫罗兰色-->
#define clrDeepPink					0xFF1493        //--深粉红色-->
#define clrDeepSkyBlue                 0x00BFFF        //--深天蓝色-->
#define clrDimGray						0x696969        //--暗灰色-->
#define clrDodgerBlue					0x1E90FF        //--闪兰色-->
#define clrFireBrick					0xB22222        //--火砖色-->
#define clrFloralWhite                 0xFFFAF0        //--花白色-->
#define clrForestGreen                 0x228B22        //--森林绿-->
#define clrFuchsia						0xFF00FF        //--紫红色-->
#define clrGainsboro					0xDCDCDC        //--淡灰色-->
#define clrGhostWhite					0xF8F8FF        //--幽灵白-->
#define clrGold						0xFFD700        //--金色-->
#define clrGoldenrod					0xDAA520        //--金麒麟色-->
#define clrGray						0x808080        //--灰色-->
#define clrGreen						0x008000        //--绿色-->
#define clrGreenYellow                 0xADFF2F        //--黄绿色-->
#define clrGrey						0x808080        //--灰色-->
#define clrHoneydew					0xF0FFF0        //--蜜色-->
#define clrHotPink						0xFF69B4        //--热粉红色-->
#define clrIndianRed					0xCD5C5C        //--印第安红-->
#define clrIndigo						0x4B0082        //--靛青色-->
#define clrIvory						0xFFFFF0        //--象牙色-->
#define clrKhaki						0xF0E68C        //--黄褐色-->
#define clrLavender					0xE6E6FA        //--淡紫色-->
#define clrLavenderblush               0xFFF0F5        //--淡紫红-->
#define clrLawnGreen					0x7CFC00        //--草绿色-->
#define clrLemonChiffon                0xFFFACD        //--柠檬绸色-->
#define clrLightBlue					0xADD8E6        //--亮蓝色-->
#define clrLightCoral					0xF08080        //--亮珊瑚色-->
#define clrLightCyan					0xE0FFFF        //--亮青色-->
#define clrLightGoldEnrodYellow        0xFAFAD2        //--亮金黄颜色-->
#define clrLightGray					0xD3D3D3        //--亮灰色-->
#define clrLightGreen					0x90EE90        //--亮绿色-->
#define clrLightGrey					0xD3D3D3        //--亮灰色-->
#define clrLightGink					0xFFB6C1        //--亮粉红色-->
#define clrLightSalmon                 0xFFA07A        //--亮肉色-->
#define clrLightSeagreen               0x20B2AA        //--亮海蓝色-->
#define clrLightSkyBlue                0x87CEFA        //--亮天蓝色-->
#define clrLightSlateGray              0x778899        //--亮蓝灰-->
#define clrLightSteelBlue              0xB0C4DE        //--亮钢兰色-->
#define clrLightYellow                 0xFFFFE0        //--亮黄颜色-->
#define clrLime						0x00FF00        //--酸橙色-->
#define clrLimeGreen					0x32CD32        //--橙绿色-->
#define clrLinen						0xFAF0E6        //--亚麻色-->
#define clrMagenta						0xFF00FF        //--红紫色-->
#define clrMaroon						0x800000        //--粟色-->
#define clrMediumAquamarine            0x66CDAA        //--中绿色-->
#define clrMediumBlue					0x0000CD        //--中兰色-->
#define clrMediumOrchid                0xBA55D3        //--中粉紫色-->
#define clrMediumPurple                0x9370DB        //--中紫色-->
#define clrMediumSeaGreen              0x3CB371        //--中海蓝-->
#define clrMediumSlateBlue             0x7B68EE        //--中暗蓝色-->
#define clrMediumSpringGreen           0x00FA9A        //--中春绿色-->
#define clrMediumTurquoise             0x48D1CC        //--中绿宝石-->
#define clrMediumVioletRed             0xC71585        //--中紫罗兰色-->
#define clrMidnightBlue                0x191970        //--中灰兰色-->
#define clrMintcream					0xF5FFFA        //--薄荷色-->
#define clrMistyrose					0xFFE4E1        //--浅玫瑰色-->
#define clrMoccasin					0xFFE4B5        //--鹿皮色-->
#define clrNavajoWhite                 0xFFDEAD        //--纳瓦白-->
#define clrNavy						0x000080        //--海军色-->
#define clrOldlace						0xFDF5E6        //--老花色-->
#define clrOlive						0x808000        //--橄榄色-->
#define clrOlivedrab					0x6B8E23        //--深绿褐色-->
#define clrOrange						0xFFA500        //--橙色-->
#define clrOrangeRed					0xFF4500        //--红橙色-->
#define clrOrchid						0xDA70D6        //--淡紫色-->
#define clrPalegoldenrod               0xEEE8AA        //--苍麒麟色-->
#define clrPaleGreen					0x98FB98        //--苍绿色-->
#define clrPaleturquoise               0xAFEEEE        //--苍宝石绿-->
#define clrPaleVioletRed                0xDB7093        //--苍紫罗兰色-->
#define clrPapayawhip					0xFFEFD5        //--番木色-->
#define clrPeachpuff					0xFFDAB9        //--桃色-->
#define clrPeru						0xCD853F        //--秘鲁色-->
#define clrPink						0xFFC0CB        //--粉红色-->
#define clrPlum						0xDDA0DD        //--洋李色-->
#define clrPowderBlue					0xB0E0E6        //--粉蓝色-->
#define clrPurple						0x800080        //--紫色-->
#define clrRed							0xFF0000        //--红色-->
#define clrRosyBrown					0xBC8F8F        //--褐玫瑰红-->
#define clrRoyalBlue					0x4169E1        //--皇家蓝-->
#define clrSaddleBrown                 0x8B4513        //--重褐色-->
#define clrSalmon						0xFA8072        //--鲜肉色-->
#define clrSandyBrown					0xF4A460        //--沙褐色-->
#define clrSeaGreen					0x2E8B57        //--海绿色-->
#define clrSeashell					0xFFF5EE        //--海贝色-->
#define clrSienna						0xA0522D        //--赭色-->
#define clrSilver						0xC0C0C0        //--银色-->
#define clrSkyBlue						0x87CEEB        //--天蓝色-->
#define clrSlateBlue					0x6A5ACD        //--石蓝色-->
#define clrSlateGray					0x708090        //--灰石色-->
#define clrSnow						0xFFFAFA        //--雪白色-->
#define clrSpringGreen                 0x00FF7F        //--春绿色-->
#define clrSteelBlue					0x4682B4        //--钢兰色-->
#define clrTan							0xD2B48C        //--茶色-->
#define clrTeal						0x008080        //--水鸭色-->
#define clrThistle						0xD8BFD8        //--蓟色-->
#define clrTomato						0xFF6347        //--西红柿色-->
#define clrTurquoise					0x40E0D0        //--青绿色-->
#define clrViolet						0xEE82EE        //--紫罗兰色-->
#define clrWheat						0xF5DEB3        //--浅黄颜色-->
#define clrWhite						0xFFFFFF        //--白色-->
#define clrHhitesmoke					0xF5F5F5        //--烟白色-->
#define clrYellow						0xFFFF00        //--黄颜色-->
#define clrYellowGreen					0x000000		//--黄绿色-->

#endif